[package]
name = "feature-configuration-scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
colored = "3.0.0"
crates_io_api = "0.11.0"
itertools = "0.14.0"
reqwest = "0.12.15"
