[package]
name = "v8"

[dependencies]
example = { version = "1.23.1", features = [
    "e_commerce",
    "catalogue",
    "list",
    "payment_method",
    "credit_card",
    "check",
    "basket"
] }
