[package]
name = "feature-configuration-postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
configuration = { version = "1.0.1", path = "../configuration" }
postgres = "0.19.11"
semver = "1.0.27"
toml = "0.9.7"
