[package]
name = "parse-size"
version = "1.1.0"
authors = ["kennytm <kennytm@gmail.com>"]
edition = "2021"
description = "Parse byte size into integer accurately."
keywords = ["bytes", "size", "humanize", "human", "parser"]
repository = "https://github.com/kennytm/parse-size"
license = "MIT"
rust-version = "1.81.0"

[features]
# This feature has been deprecated and does nothing.
std = []

[dev-dependencies]
clap = { version = "4.5", default-features = false, features = ["std", "derive"] }
